server:
  servlet:
    context-path: /fee
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:fee
    driverClassName: org.h2.Driver
    username: fee
    password: fee
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
